fixtures:
  repositories:
    puppetlabs-stdlib:
      repo: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref:  "4.6.0"
    puppet-archive:
      repo: "git://github.com/voxpupuli/puppet-archive.git"
      branch:  "master"
  symlinks:
    vodafone_java: "#{source_dir}"
